# Generated by Django 5.2.8 on 2025-11-16 12:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 8), ("paragraph", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The main title for the hero section.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The subtitle that appears below the main title.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The background image for the hero section.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "The URL the button will link to",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "is-primary",
                            "help_text": "Bulma CSS classes for styling (e.g., 'is-primary', 'is-light is-outlined')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4), ("class_str", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {
                            "help_text": "Add up to two call-to-action buttons.",
                            "max_num": 2,
                            "min_num": 0,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("hero_title", 0),
                                ("hero_subtitle", 1),
                                ("hero_image", 2),
                                ("hero_buttons", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "template": "blocks/rich_text_block.html"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="A subtitle for the home page",
                max_length=255,
                null=True,
            ),
        ),
    ]
