# Generated by Django 5.2.8 on 2025-11-16 13:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="mission_vision",
            field=wagtail.fields.StreamField(
                [("mission_vision", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the point (e.g., Education)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The description for the point.",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.ListBlock",
                        (2,),
                        {"help_text": "Add mission points to display."},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("points", 3)]], {}),
                },
                help_text="The mission and vision section",
                null=True,
            ),
        ),
    ]
