# Generated by Django 5.2.8 on 2025-11-16 14:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_featured_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="featured_programs",
            field=wagtail.fields.StreamField(
                [("featured_programs", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the program.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "A short description of the program.",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The image for the program card.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "The page to link to for this program.",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("short_description", 1),
                                ("image", 2),
                                ("page", 3),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="The featured programs section",
                null=True,
            ),
        ),
    ]
