# Generated by Django 5.2.8 on 2025-11-16 14:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_featured_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="mission_vision",
            field=wagtail.fields.StreamField(
                [("mission_vision", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Featured Programs",
                            "help_text": "The title of the section.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The subtitle for the section.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of the program.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "A short description of the program.",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "The image for the program card.",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "The page to link to for this program.",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("short_description", 3),
                                ("image", 4),
                                ("page", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {"help_text": "Add program cards to display."},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "See All Programs",
                            "help_text": "Text for the 'See All Programs' button.",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "The page to link to for the 'See All Programs' button.",
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("programs", 7),
                                ("see_all_button_text", 8),
                                ("see_all_button_page", 9),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="The mission and vision section",
                null=True,
            ),
        ),
    ]
